matthew-brett/delocate

- delocate/delocating.py
- delocate/tests/test_delocating.py
- delocate/tests/test_scripts.py
- delocate/tests/test_wheelies.py
- scripts/delocate-path
- scripts/delocate-wheel
Previously delocate_path and delocate_wheel were only looking for dependencies
in files with extensions '.dylib' or '.so'.  Change the default to look in all
files.  Add argument for scripts and functions to choose previous behavior.
> RF: change default delocation to look in all files

- README.rst
Addresses #16.
The only way I know of formatting text within a link as code is
```rst
`:code:`auditwheel` <https://github.com/pypa/auditwheel>`_
```
This works locally (with `rst-preview-pandoc@0.1.12` in `atom`), but doesn't render properly on GitHub, so I let the package's name be plain text.
> DOC: link to `auditwheel` from README

- delocate/tools.py
Trailing periods also may or may not exist in xcode messages.
Testing for strings within xcode messages will be more reliable and future proof than testing that xcode messages have specific beginnings or endings.
I needed this patch to delocate macosx wheels using XCode 8.2.1.
> Allow for xcode command line tools names in output

- delocate/delocating.py
- delocate/tests/test_tools.py
- delocate/tests/test_wheelies.py
- delocate/tools.py
If a binary file is signed, tools like install_name_tool will invalidate
the signature by changing the file contents.  Later versions of MacOS
refuse to load binary files with invalid signatures.
This adds a new function which overwrites bad signatures with an ad-hoc
signature.  This is as close as you can get to removing the signature
using the available tools in MacOS.
> Replace invalidated signatures in delocated libraries.

- .travis.yml
- MANIFEST.in
- delocate/tests/data/some_code.py
- delocate/tests/test_install_names.py
- delocate/tools.py
- setup.py
Latest otool (900) has different not-object error messages.
Refactor routines reading otool output to deal with these error
messages.  Refactor get_rpaths to use the more general machinery.
> BF: add fixes for latest otool

- delocate/tools.py
Fixes https://github.com/matthew-brett/delocate/issues/42
When zipping the wheel, we need to set `stat.S_IFREG` (for regular files) in the `ZipInfo.external_attr` attribute.
If we don't do that, then upon installing the wheel with pip, any files that had executable flags (e.g. embedded executables) in the wheel will lose them.
Pip restores the execute permissions when uncompressing the wheel only if `stat.S_ISREG(mode)` is True:
https://github.com/pypa/pip/blob/35f098363983baebc13ffb84ded80b816d8fb246/src/pip/_internal/utils/misc.py#L488-L493
> set S_IFREG (regular file) in ZipInfo.external_attr

- delocate/tools.py
Sometime between cctools-900 and cctools-949, the `otool` utility on
OS X made a one-character change in its 'this isn't an object file'
message.  The old message was:
'Object is not a Mach-O file type'
and the new one is
'object is not a Mach-O file type'.
I've added a new line to `BAD_OBJECT_TESTS` in tools.py to check for
the new version.
> Update "not an object" table for cctools-949

- README.rst
As discussed in Issue #12, Issue #15, and elsewhere
delocate-wheel may ignore compiled extensions at the
top level of a wheel that are not part of a Python
package.  This documents that limitation and shows
how the package structure can be adjuste to fix it.
> Doc limitation with top-level Py module structure

- .travis.yml
- delocate/tests/test_fuse.py
- delocate/tests/test_tools.py
- delocate/tests/test_wheelies.py
- delocate/tools.py
- test-requirements.txt
Fix for new format of Cataline otool output.
Fix for 'wheel' binary not on path.
> MRG: fix for Catalina otool; wheel binary

- delocate/tests/test_tools.py
- delocate/tools.py
Fix regexp to escape characters for names like `name++`
> add escape of character in name of library

- .travis.yml
Updates multibuild to include https://github.com/matthew-brett/multibuild/pull/385, and then updates variables for the Python 2.7 job to fix a [failing build](https://travis-ci.org/github/radarhere/delocate/builds/760282731) (see https://github.com/matthew-brett/delocate/pull/86#issuecomment-751310477)
Suggested in https://github.com/matthew-brett/delocate/pull/86#issuecomment-784817548
> Updated multibuild to work around end of pip support

- doc/links_names.inc
Navigating to http://pypi.python.org/pypi/delocate in your browser, you are redirected to https://pypi.org/project/delocate/
> Updated URL

- delocate/tests/test_tools.py
- delocate/tools.py
cc @mattip
In macOS arm64, all executables and shared libraries are required to be signed with a valid signature and it can be an ad-hoc signature. Otherwise the process is killed.
> Ad-hoc sign binaries after change

- .github/workflows/testing.yml
With the `i386` files dropped I was finally able to finish this.
This workflow rebuilds the test data and uploads it as an artifact, which means I can commit it back into the repository on my own.  It also runs the standard tests to verify that they work.
> Add GitHub workflow to build test data and run tests.

- .travis.yml
- README.rst
- setup.py
Drop automated testing for Python < 3.6.
When this PR is merged, new code can use Python 3.6 features such as type annotation, 
f-strings and insertion-order dictionaries.
I suggest we strip out the Python 2.7 back-compatibility code gradually, as we do other 
edits on the code.
Closes gh-109.
> Drop claim to support Python < 3.6

- .flake8
- .github/workflows/python-linters.yml
- delocate/delocating.py
- delocate/libsana.py
- delocate/tests/test_delocating.py
- delocate/tests/test_libsana.py
- delocate/tools.py
- wheel_makers/fakepkg2/setup.py
- wheel_makers/fakepkg_rpath/setup.py
This sets which error codes to select and ignore.  The previous config was using parts of my local configuration which was undesirable.
The GitHub workflow now uses a simpler problem matcher action and was reformatted.
Any new Flake8 errors were fixed.
> Update Flake8 config and workflow.

- Changelog
- delocate/delocating.py
- delocate/tests/test_wheelies.py
Combines lib_flit_func and copy_flit_func behavior into one function.
This makes sure that a file which won't be copied will not have its dependencies analyzed.
Fixes #119
> Don't follow libraries which won't be copied.

- .github/workflows/testing.yml
- README.rst
- test-requirements.txt
Added the code coverage tools to the workflow.  There's an option to set up a YAML file but it isn't required and I haven't done it.
[The public site is here.](https://app.codecov.io/gh/matthew-brett/delocate/branch/codecov)  It already shows the coverage of my PR.  I've added a badge to the readme.
I don't really know how to handle coverage correctly without doing a development install.  I now run two tests, one for code coverage and one that's isolated from the repository.
> Support public code coverage statistics.

- delocate/delocating.py
I played with *args and **kwargs to warn on positional arguments here, but all
the solutions looked like they would make type-hinting more obscure, so I gave
up.
We can just raise an error for non-keyword arguments later.  It's a pretty
obvious fix for our users.
> MRG: fix for docstring

- .mailmap
- Changelog
- README.rst
Doing this publicly to be sure I haven't missed anything.  It'll be a good idea to release a version with #123 merged before anyone can make another issue about it.
Updated `.mailmap` with duplicates.
Added a PyPI status badge.  This links to the PyPI package and states the current version.
Removed library-not-bundled troubleshooting section since that's now been fixed.
Changelog updated for this release.
Sorry if I'm requesting reviews from you too often, I don't really know an alternative other than no reviews at all.
Ready to merge.  After that I'll push a `0.10.0` tag which will deploy this release.
> Release 0.10.0

- Changelog
- delocate/libsana.py
- delocate/tests/test_delocating.py
- delocate/tests/test_libsana.py
Resolves issue #133.
I have managed to reproduce the issue by the following minimal case:
We have:
```
liba.dylib
links/liba.dylib, a soft link to liba.dylib
```
and
```
libb.dylib, depends on liba.dylib via `@rpath/liba.dylib`
links/libb.dylib, depends on links/liba.dylib and been found via `DYLD_LIBRARY_PATH`
```
During resolving dependencies, the first is found via resolving from `@rpath` by `resolve_dynamic_paths`, and the later is resolved from `DYLD_LIBRARY_PATH` by `search_environment_for_lib`, where the soft link path is returned, thus the conflicit happens.
For more details, see the minimal reproduce case in `test_tree_libs_from_directory_with_links`, and we have verified the patch in our real-world wheels that triggerred #133 before.
> Avoid duplication when library has soft links and been used in the same wheels.

- Changelog
- delocate/pkginfo.py
- delocate/tests/test_wheeltools.py
- delocate/wheeltools.py
- setup.py
The plans to remove the `wheel.pkginfo` module can be negotiated with the `wheel` devs, but this PR should cause less drama.
Adds `delocate.pkginfo` to read/write these files, based on the original module.
Removes code supporting `wheel<0.32.0`.  Adds code to support the unreleased versions of `wheel>0.37.1`.
Adds type hinting to the relevant functions.
Closes #135
> Replicate the to-be-removed `wheel.pkginfo` module.

- .github/workflows/testing.yml
- .travis.yml
- Changelog
- delocate/tests/test_install_names.py
- delocate/tests/test_tools.py
- delocate/tools.py
- pyproject.toml
- test-requirements.txt
It's likely that `otool` changed its output since #78 and `parse_install_name` needs to be updated again.
So far this changes the function so that it outputs the input string when it fails, which will make this easier to fix in the future.  I also added tests for macOS 11 and Xcode 13 but they didn't fail.
Refactors how otool install names are parsed which fixes #78.
> Update `parse_install_name` to the latest format.

- .mypy.ini
- .travis.yml
- Changelog
- pyproject.toml
- setup.py
- wheel_makers/make_wheels.sh
Python 3.6 has reached end-of-life: https://endoflife.date/python
Python 3.7 has postponed evaluations of annotations which I'd like to start using: https://docs.python.org/3/whatsnew/3.7.html
> Drop Python 3.6.

- .github/workflows/testing.yml
- Changelog
- delocate/tests/test_scripts.py
- delocate/tests/test_wheeltools.py
- delocate/wheeltools.py
- setup.py
Based on feedback from https://github.com/pypa/wheel/issues/433.  There are plans on refactoring wheel which will likely break Delocate again.  This PR will prevent that from happening.
Small single-used wheel functions are now inline.  The packaging module was added which has a stable API for parsing wheel names.  Type hinting added to relevant functions.
> Remove dependencies on wheels unstable API.

- delocate/tools.py
The previous merges caused a logical conflict.
Since Python 3.7 is now the lowest version, type hints can now be deferred outside of runtime.  This fixes the error with `subprocess.CompletedProcess[str]` which is not available at runtime on older Python versions.
I'm merging this as soon as tests pass.
> Use future annotations.

- delocate/libsana.py
A new version of Mypy detected this issue, and will raise errors until it's fixed.
This code was copied from other places. It's intended that this isn't an optional function here, so I'm removing the extra check.
> Remove always True function check.

- Changelog
- delocate/libsana.py
- delocate/tests/test_libsana.py
Fixes https://github.com/matthew-brett/delocate/issues/155 and fixes the issues in https://github.com/numpy/numpy/pull/22525
> search in /usr/local/lib and /usr/lib like the system loader

- delocate/tests/test_install_names.py
- delocate/tests/test_tools.py
- delocate/tools.py
Mach-O executables and libraries begin with a magic number. It's much faster to read the first few bytes of a file than to spawn `otool`.
For example, `delocate list-deps` currently takes about 12 minutes on the PyTorch macOS wheels (and nearly twice as long on GitHub's CI runners). With this change, `delocate list-deps` instead takes about 40 seconds.
> Speed-up delocate on large wheels.

- .github/workflows/python-package.yml
- Changelog
- delocate/tools.py
The `unzip` command on MacOS does not seem to handle Python's UTF-8 locale correctly. Running `unzip -q` should skip outputting these non-ASCII filenames in otherwise working runs.
In theory this change may also improve the performance of large archives.
Fixes #181
> Suppress filename output in unzip call.

- .github/workflows/python-package.yml
Added `macos-13` and Python 3.11 to the workflows.
Updated older actions to the latest versions, removing deprecation warnings.
Changed Windows runner to always use the latest version.
I'm not sure who should review these.  I may just merge this myself sometime after tests pass.
> Update versions on workflows.  Add `macos-13` job.

- delocate/tests/test_tools.py
- delocate/tests/test_wheelies.py
- delocate/tests/test_wheeltools.py
- delocate/tools.py
It was suggested [here](https://github.com/matthew-brett/delocate/issues/181#issuecomment-1544388928) to port the zip functions from auditwheel.
Changes were made to fit Delocate's test conditions and use-cases and to clean up these functions.
Calls to the `unzip` command were removed, Windows can now test these functions.
> Refactor zip functions.

- Changelog
- delocate/tests/env_tools.py
- delocate/tests/test_wheelies.py
- delocate/tools.py
https://reproducible-builds.org/docs/source-date-epoch/
> Support for SOURCE_DATE_EPOCH (reproducible builds)

- pyproject.toml
- setup.py
I didn't notice to set scripts as dynamic in pyproject.toml when I first set it up. This caused deprecated behavior which recently caused the scripts to go missing during tests and in general. This issue shouldn't affect installs from wheels, only manual installs.
I moved all scripts to pyproject.toml as that's more portable and will reduce reliance on setup.py.
> Move console scripts to pyproject.toml

- Changelog
- delocate/cmd/common.py
- delocate/cmd/delocate_addplat.py
- delocate/cmd/delocate_fuse.py
- delocate/cmd/delocate_listdeps.py
- delocate/cmd/delocate_patch.py
- delocate/cmd/delocate_path.py
- delocate/cmd/delocate_wheel.py
- delocate/tests/test_scripts.py
Same motivation as https://github.com/pypa/auditwheel/pull/310
I need this to remove libvulkan from the repaired wheel.
> Add --exclude option to delocate-wheel

- Changelog
- delocate/cmd/common.py
- delocate/delocating.py
- delocate/tests/test_scripts.py
- delocate/tools.py
Fixes https://github.com/matthew-brett/delocate/issues/101
> Option to sanitize rpaths

- .flake8
- .github/workflows/python-package.yml
- .pre-commit-config.yaml
- .vscode/settings.json
- CONTRIBUTING.md
- delocate/cmd/common.py
- delocate/cmd/delocate_addplat.py
- delocate/cmd/delocate_fuse.py
- delocate/cmd/delocate_listdeps.py
- delocate/cmd/delocate_patch.py
- delocate/cmd/delocate_path.py
- delocate/cmd/delocate_wheel.py
- delocate/delocating.py
- delocate/fuse.py
- delocate/libsana.py
- delocate/tests/conftest.py
- delocate/tests/data/fakepkg2.bad_patch
- delocate/tests/test_delocating.py
- delocate/tests/test_fuse.py
- delocate/tests/test_libsana.py
- delocate/tests/test_scripts.py
- delocate/tests/test_wheelies.py
- delocate/tests/test_wheeltools.py
- delocate/wheeltools.py
- pyproject.toml
- setup.py
This replaces Flake8 and all of the formatting tools I've previously added with Ruff, which includes the features of all the other tools combined while also being fast enough to be used as a pre-commit hook, which I've also setup in this PR.
I've also added a `CONTRIBUTING.md` with everything important I could remember about this project.
> Replace black/isort/flake8 with Ruff and pre-commit

- delocate/cmd/common.py
- delocate/cmd/delocate_addplat.py
- delocate/cmd/delocate_fuse.py
- delocate/cmd/delocate_listdeps.py
- delocate/cmd/delocate_patch.py
- delocate/cmd/delocate_path.py
- delocate/cmd/delocate_wheel.py
- delocate/tests/test_scripts.py
Followed the [upgrade guide](https://docs.python.org/3.12/library/argparse.html#upgrading-optparse-code) on the Python docs.
Now has explicit positional arguments. Moved parser definitions to the top-level to give more room for help strings and parameters and to technically allow debugging of the parser. Shared arguments converted into parser parents. Most redundant code has been moved to the shared module.
I imagine some `help` and `metavar` parameters can still be tuned. I didn't come up with a `help` for every positional argument.
Closes #110
> Refactor commands to use argparse

- Changelog.md
- delocate/delocating.py
Replaces `directory.endswith(package_name)` with the more exact `Path(directory).name == package_name`.
I didn't find any other determinism issues in this function.
I think `find_package_dirs` shouldn't have returned a set, since it operates on `os.listdir` it should've returned a list instead, but that doesn't really matter
Fixes #192
> Use exact directory name to decide dylib files directory

- .vscode/settings.json
- Changelog.md
- delocate/cmd/common.py
- delocate/cmd/delocate_addplat.py
- delocate/cmd/delocate_listdeps.py
- delocate/cmd/delocate_path.py
- delocate/cmd/delocate_wheel.py
- delocate/tests/test_scripts.py
Expands globs in simple cases using the following rules:
* If any path is a existing folder or file then it's used as-is, even if it can be used as a glob pattern. This is supposed to ensure that there's no surprises or regressions.
* Otherwise the glob is expanded with Python's `glob` module. If this results in no files then it raises `FileNotFoundError`.
Added tests for this.
Some commands are too complex for this workaround. This only applies to commands which takes one list of arguments and not commands with more complex positional parameters such as `delocate-fuse` and `delocate-patch`.
I'd rather not merge this PR until it's reviewed.
Fixes #71
> Expand globs in simple script arguments

- delocate/delocating.py
Some build systems (e.g., Bazel) generate read-only artifacts, and `shutil.copy` also copies these modes.
Auditwheel has the same logic [here](https://github.com/pypa/auditwheel/blob/db7962149a3e971eba3974a58edcb2226c787f8d/src/auditwheel/repair.py#L160-L162).
> After copying a lib to the wheel directory, set its writeable bit if necessary

- delocate/libsana.py
- delocate/tools.py
Don't assume that multi-path environment variables like `DYLD_LIBRARY_PATH` are split by `":"`.
> Use os.pathsep instead of hard coding ':'

- Changelog.md
- delocate/delocating.py
- delocate/tests/test_scripts.py
Adds clear instructions for how to update the MacOS target version when the current target is not met.
Closes #211
> Improve error message for when a MacOS target version is not met

- Changelog.md
- README.rst
- delocate/cmd/delocate_fuse.py
- delocate/cmd/delocate_merge.py
- delocate/delocating.py
- delocate/fuse.py
- delocate/tests/test_delocating.py
- delocate/tests/test_scripts.py
- delocate/wheeltools.py
- pyproject.toml
This is my attempt at a PR for #174.
This adds the ability to "retag" a universal2 fused wheel. When running delocate-fuse with this flag, it will update the filename and the dist-info file of the fused wheel to reflect that it is a universal2 wheel.
I didn't update the readme or add any tests yet. I wanted to first get feedback on whether or not this is the "retag" you had in mind.
Let me know what you think/if there is anything you would like changed!
> Retag wheels automatically when fusing

- Changelog.md
- delocate/delocating.py
- delocate/tests/test_delocating.py
- delocate/tests/test_libsana.py
- delocate/tests/test_wheelies.py
Thanks for this awesome project!
I noticed tonight that an error message is printing with the literal string `f{lib_path}` in it, like this:
> delocate.libsana.DelocationError: f{lib_path} already exists in wheel but need to copy /opt/homebrew/Cellar/libomp/17.0.6/lib/libomp.dylib
I strongly suspect that was supposed to be an f-string, where `{lib_path}` is replaced in the error message with a path to a library.
This proposes that fix.
> fix string formatting in error message

- Changelog.md
- delocate/cmd/delocate_wheel.py
- delocate/delocating.py
- delocate/tests/test_wheelies.py
Currently, there is no way to customize libs dir if the wheel has no package directory.
One use case is an extension, that offers C-API (like the gmpy2 package).  With above patch you could set one to something common for all platforms.
> If wheel has no package directories, use lib_sdir as a suffix

- .github/workflows/python-package.yml
Replaces my API token with trusted publishing as described in #196. Closes #196
I have enough access to handle on rest on PyPI but a GitHub user can't setup an environment on another users private repo. @matthew-brett will need to do the following:
* On this repo, go to: Setting > Enviroments > New environment
* Name the new environment: `deploy`
* Optionally setup deployment protection rules
Only then can I finish this PR.
> Configure trusted publishing

- Changelog.md
- delocate/cmd/common.py
- delocate/tests/test_scripts.py
adopts #101  as default behavior with new `--no-sanitize-rpaths` opt-out. `--sanitize-rpaths` kept for backward compatibility.
> sanitize rpaths by default

- .github/workflows/python-package.yml
I merged #220 too early. @webknjaz has suggested several small tweaks to that PR, this PR applies them. My initial configuration was outdated.
Apologies to @matthew-brett, if you setup any of the optional security stuff with the `deploy` environment then you should do the same with a `pypi` environment. If you didn't do any of the extras then apparently the environment will be automatically created on-demand and you won't need to do anything.
> Apply suggestions to the deployment workflow

- .pre-commit-config.yaml
- CONTRIBUTING.md
- Changelog.md
- README.rst
Update readme to mention delocate-merge instead of delocate-fuse, change TravisCI URL to GitHub Actions.
Update release instructions
Update and run pre-commit hooks
I really should've taken the initiative and performed this release sooner. The readme had mentioned unreleased features for too long, and there were pending bug fixes.
> Prepare 0.12.0 release

- .github/workflows/python-package.yml
- CONTRIBUTING.md
- Changelog.md
- delocate/libsana.py
- delocate/tests/test_install_names.py
- delocate/tools.py
- delocate/wheeltools.py
- pyproject.toml
`get_dependencies` and what it calls has been refactored to handle dependencies organized by architecture. Delocate is now aware of multiple architectures and should handle the most common cases where libraries depend on different things depending on their architecture. Fixes #153 Fixes #154
`_check_ignore_archs` is being phased out. Most of the work was in `get_dependencies`, `get_install_names`, and `get_rpaths`. I made new private versions of some of these so that they could have an updated return value needed to track the architecture.
Adding `-arch all` to all `otool` calls makes `otool` act like it does in later MacOS versions. The tests added in #140 no longer expect `NotImplementedError`. Fixing this also allows testing on newer MacOS runners which I've added. Closes #137
I tried …
> Refactor dependency discovery to handle multiple architectures

- Changelog.md
- delocate/fuse.py
- delocate/tests/test_scripts.py
- delocate/tools.py
Updates merging to automatically detect binary files and removes the older behavior. This handles the common case of binary files having no suffix. Fixes #228
Using `_is_macho_file` has false negatives. Instead, all files are passed to the `lipo` command and its return code is used to determine if the file was valid to be merged. This might have its own issues, but I'd need to completely rewrite `lipo_fuse` to make it graceful.
The `lib_exts` parameter of `fuse_trees` is now ignored and I intend for it to be removed completely later.
This reuses old tests instead of trying to keep the old behavior. Updating the tests now could conflict with PR #234.
> Smarter detection of binary files during delocate-merge

- Changelog.md
- delocate/delocating.py
- delocate/libsana.py
- delocate/tests/test_delocating.py
- delocate/tests/test_install_names.py
- delocate/tests/test_tools.py
- delocate/tools.py
- pyproject.toml
This branch was an attempt to remove `macholib` and write a better `otool` parser but I underestimated how difficult the output of `otool` was. I wasn't able to resolve cases where it'd decide to not return the architecture info in its output because it decided it was the current systems architecture. In the end I decided it was more reliable to suppress the error from macholib instead of trying to remove the library.
This suppresses `ValueError: Unknown Mach-O header` which fixes #229, fixes #227. I don't have a fat static binary to test this such as an archive (`.a`) compiled for both `arm64` and `x86_64`.
While working on this I noticed the `-m` flag on `otool` and enabled it because delocate is always working with the whole file at once. This flag is documented as:
> -m The object …
> Ignore unparseable static libraries

- delocate/delocating.py
- delocate/tests/test_delocating.py
In some cases macholib will raise `struct.error` instead of `ValueError` such as when a file has less than 4 bytes to unpack. This issue was mentioned here: https://github.com/matthew-brett/delocate/issues/229#issuecomment-2621600344
Added a test for `_get_macos_min_version` with an empty file which triggers this error. This covers the suppressed struct.error branch.
This regression was caused by #235 which hasn't been released yet, so there's nothing to add to the changelog. I'm attempting to remove the reliance on the crudely implemented `_is_macho_file` function.
> Suppress struct unpack error from macholib

- .coveragerc
- Changelog.md
- delocate/delocating.py
- delocate/fuse.py
- delocate/tests/test_fuse.py
- delocate/tests/test_scripts.py
- delocate/wheeltools.py
- pyproject.toml
Adds the delocate version used to wheel metadata as suggested by the [Binary distribution format guidelines](https://packaging.python.org/en/latest/specifications/binary-distribution-format). The format is `delocate {version}` as shown in the guideline but I've seen other tools use `name ({version})` instead.
Tagging wheels like this will help with future issues if there's ever a long term problem with a specific version of delocate.
There seemed to be cases where `rewrite_record` could be called before modifications were done, this has been resolved.
Was also able to move `.coveragerc` into `pyproject.toml` so that's one less config file.
> Append delocate version to wheel metadata

- .pre-commit-config.yaml
- CONTRIBUTING.md
- Changelog.md
- LICENSE
- delocate/cmd/delocate_addplat.py
- delocate/fuse.py
- pyproject.toml
Add release to changelog
Update copyright year
Update pre-commit hooks and apply fixes
Update release steps with pre-commit instructions
Remove deprecated Ruff rules from ignores
Closes #243
> Prepare 0.13.0 release
